language: csharp
solution: TaskReactor/TaskReactor.sln
dotnet: 3.1
mono: none
dist: xenial
os: Windows
install:
  - dotnet build -c Release TaskReactor/TaskReactor.sln
  - dotnet test TaskReactor/TaskReactor.sln
