// <auto-generated />

using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace ApplicationDomain.Models.Database.Migrations
{
    [DbContext(typeof(TaskReactorDbContext))]
    [Migration("20200515151113_Initialization")]
    partial class InitializeMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity("ApplicationDomain.Models.Database.Entity.Schedule", b =>
                {
                    b.Property<int>("OwnerUserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("DurationOfOneTime")
                        .HasColumnType("Integer");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("Integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("Integer");

                    b.HasKey("OwnerUserId", "Title");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("ApplicationDomain.Models.Database.Entity.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("ApplicationDomain.Models.Database.Entity.Schedule", b =>
                {
                    b.HasOne("ApplicationDomain.Models.Database.Entity.User", "OwnerUser")
                        .WithMany("Schedules")
                        .HasForeignKey("OwnerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("ApplicationDomain.Models.Database.Entity.Interval", "Interval", b1 =>
                        {
                            b1.Property<int>("ScheduleOwnerUserId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("ScheduleTitle")
                                .HasColumnType("TEXT");

                            b1.Property<byte>("Kind")
                                .HasColumnType("INTEGER");

                            b1.Property<byte>("Value")
                                .HasColumnType("INTEGER");

                            b1.HasKey("ScheduleOwnerUserId", "ScheduleTitle");

                            b1.ToTable("Schedule");

                            b1.WithOwner()
                                .HasForeignKey("ScheduleOwnerUserId", "ScheduleTitle");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
