// <auto-generated />

using ApplicationDomain.Models.Database.Entity;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ApplicationDomain.Models.Database.Migrations
{
    [DbContext(typeof(TaskReactorDbContext))]
    class TaskReactorDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("ProductVersion", "3.1.4");

            modelBuilder.Entity<User>();

            // configure composition key
            modelBuilder.Entity<Schedule>(
                buildAction => buildAction!.HasKey(schedule => new {schedule.OwnerUserId, schedule.Title})
            );
        }
    }
}